CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority integer not null,
    description text,
    deliverydate date not null
);

create table if not exists tasks(
    id integer PRIMARY KEY GENERATED by DEFAULT as identity,
    name text not null check(name <> ''),
    done boolean,
    projectId integer references projects(id)
);

insert into projects (name, priority, description, deliverydate )
values('make a web app', 1 , 'Using Javascript', '2020-05-12');

insert into projects(name, priority, description, deliverydate)
values('Make and app', 1, 'Using dart' , '2020-01-02');

insert into projects(name, priority, description, deliverydate)
values('Make a desktop app', 2, 'Using c++' , '2020-01-03');

--INSERT TASK DATA
INSERT INTO tasks(name, done, projectId)
values ('download cuejs', false, 1);

INSERT INTO tasks(name, done, projectId)
values ('Create UI web', false, 1);

INSERT INTO tasks(name, done, projectId)
values ('download flutter', false, 2);

INSERT INTO tasks(name, done, projectId)
values ('Desing ui', false, 2);